### ISSUE TITLE
Hg38 bigwig generation - difference in default behaviour for deeptools and homer

### ISSUE THREAD

**Issue by JoeHarman** [alsmith151/ngs_pipeline#16]
Creating bigwigs in hg38 with homer and deeptools results in Homer tracks showing regions of absent signal, whereas normal signal is found with deeptools. These regions are not overlapping blacklist. Looking at hg19 mapping does not show this loss of signal.

I believe this is because hg38 mapping has a much higher level of multimapping compared with hg19. By default Homer retains uniquely mapped reads, and multimapping regions are lost. Adding the -keepAll parameter to homer tag directory generation fixes this issue.

Is this a parameter that we want used by default? Or maybe the template config files should have these written in?

Example tracks attached illustrating the issue. 1st track shows DeepTools, 2nd track shows Homer, 3rd track shows Homer with the -keepAll parameter.
![Screenshot 2021-07-23 at 18 45 15](https://user-images.githubusercontent.com/22264529/126821246-fbda2221-aeba-48f6-ac75-c0d2c2f69454.png)

**Comment by alsmith151** [comment]
That's interesting, I've not spotted this but have mainly been using hg19. You're right it might be worth adding a note about this or including this flag in the config.yml.

Will get around to adding this/ you could always clone and generate a PR.

**Comment by alsmith151** [comment]
fixed by #18
